In [1]:
import napari
from pathlib import Path
from skimage.io import imread
import pandas as pd

viewer = napari.Viewer()

# Using pathlib.Path.cwd() to get current working directory
current_dir = Path.cwd()
print(f"Current working directory: {current_dir}")

# Get the notebook's directory (same as current working directory in Jupyter)
notebook_dir = Path.cwd()

# Construct path to sample data
path = notebook_dir / "src" / "napari_clusters_plotter" / "sample_data" / "BBBC007_v1_images" / "A9"
print(f"Sample data path: {path}")
print(f"Path exists: {path.exists()}")

label_filename = path / "A9 p5d_labels.tif"
feature_filename = path / "A9 p5d_features.csv"

labels = imread(label_filename)
features = pd.read_csv(feature_filename)
translate = labels.shape[-1]
viewer.add_labels(
    labels,
    name=label_filename.stem,
    features=features,
)

label_filename = path / "A9 p7d_labels.tif"
feature_filename = path / "A9 p7d_features.csv"
labels = imread(label_filename)
features = pd.read_csv(feature_filename)

viewer.add_labels(
    labels,
    name=label_filename.stem,
    features=features,
    translate=(0, translate)
)

Current working directory: c:\Users\mazo260d\Documents\GitHub\napari-clusters-plotter
Sample data path: c:\Users\mazo260d\Documents\GitHub\napari-clusters-plotter\src\napari_clusters_plotter\sample_data\BBBC007_v1_images\A9
Path exists: True

In [2]:
for layer in viewer.layers:
    if hasattr(layer, 'features') and layer.features is not None:
        print(f"Layer: {layer.name}, Features: {layer.features.shape}")
        layer.features.insert(1, 'layer_name', layer.name)
        layer.features['layer_name'] = layer.features['layer_name'].astype('category')
        print(layer.features.head())

Layer: A9 p5d_labels, Features: (111, 10)
   label     layer_name  area_filled  perimeter  axis_major_length  \
0      1  A9 p5d_labels        153.0  53.591883          20.634990
1      2  A9 p5d_labels        194.0  58.384776          20.766166
2      3  A9 p5d_labels        222.0  54.384776          18.962272
3      4  A9 p5d_labels        131.0  47.591883          18.501388
4      5  A9 p5d_labels         17.0  16.207107          10.247243

   axis_minor_length  eccentricity   area  intensity_mean  intensity_max  \
0          10.457447      0.862074  153.0       56.516340          102.0
1          13.044210      0.778095  194.0       94.010309          180.0
2          15.446029      0.580070  222.0       78.220721          137.0
3           9.996370      0.841470  131.0       64.198473          113.0
4           1.959159      0.981553   17.0       61.823529           78.0

   intensity_min
0           26.0
1           30.0
2           26.0
3           29.0
4           47.0
Layer: A9 p7d_labels, Features: (152, 11)
   label     layer_name  area_filled  perimeter  axis_major_length  \
0      1  A9 p7d_labels           53  28.899495          12.174922
1      2  A9 p7d_labels           75  34.863961          15.289337
2      3  A9 p7d_labels           72  35.899495          15.134952
3      4  A9 p7d_labels           94  35.313708          12.044548
4      5  A9 p7d_labels           80  37.899495          17.386004

   axis_minor_length  eccentricity  area  intensity_mean  intensity_max  \
0           5.937179      0.873036    53       71.754717            102
1           6.448131      0.906717    75       50.333333             80
2           6.638217      0.898682    72       46.361111             85
3          10.240076      0.526486    94       70.723404             99
4           6.125917      0.935869    80       80.662500            140

   intensity_min  extra_feature
0             40              2
1             36              4
2             30              6
3             37              8
4             27             10

In [3]:
viewer.layers.selection

Selection({<Labels layer 'A9 p7d_labels' at 0x2223ab23f50>, <Labels layer 'A9 p5d_labels' at 0x2223ab23b60>})

In [7]:
# if selection changed
df_list = []
for layer in list(viewer.layers.selection):
    if hasattr(layer, 'features') and layer.features is not None:
        print(f"Selected Layer: {layer.name}, Features: {layer.features.shape}")
        if "layer_name" not in layer.features.columns:
            layer.features.insert(1, 'layer_name', layer.name)
            layer.features['layer_name'] = layer.features['layer_name'].astype('category')
        df_list.append(layer.features)

table = pd.concat(df_list)
table_inner = pd.concat(df_list, join='inner')

Selected Layer: A9 p7d_labels, Features: (152, 12)
Selected Layer: A9 p5d_labels, Features: (111, 11)

In [11]:
table.head(3)

,label,layer_name,area_filled,perimeter,axis_major_length,axis_minor_length,eccentricity,area,intensity_mean,intensity_max,intensity_min,extra_feature
0,1,A9 p7d_labels,53.0,28.899495,12.174922,5.937179,0.873036,53.0,71.754717,102.0,40.0,2.0
1,2,A9 p7d_labels,75.0,34.863961,15.289337,6.448131,0.906717,75.0,50.333333,80.0,36.0,4.0
2,3,A9 p7d_labels,72.0,35.899495,15.134952,6.638217,0.898682,72.0,46.361111,85.0,30.0,6.0

In [12]:
table.tail(3)

,label,layer_name,area_filled,perimeter,axis_major_length,axis_minor_length,eccentricity,area,intensity_mean,intensity_max,intensity_min,extra_feature
108,109,A9 p5d_labels,296.0,64.041631,21.987787,17.280386,0.618343,296.0,72.601351,146.0,27.0,NaN
109,110,A9 p5d_labels,46.0,24.485281,10.281764,5.986901,0.812986,46.0,52.065217,61.0,40.0,NaN
110,111,A9 p5d_labels,87.0,39.520815,17.591475,6.785633,0.922610,87.0,68.678161,99.0,37.0,NaN

In [13]:
table_inner.head(3)

,label,layer_name,area_filled,perimeter,axis_major_length,axis_minor_length,eccentricity,area,intensity_mean,intensity_max,intensity_min
0,1,A9 p7d_labels,53.0,28.899495,12.174922,5.937179,0.873036,53.0,71.754717,102.0,40.0
1,2,A9 p7d_labels,75.0,34.863961,15.289337,6.448131,0.906717,75.0,50.333333,80.0,36.0
2,3,A9 p7d_labels,72.0,35.899495,15.134952,6.638217,0.898682,72.0,46.361111,85.0,30.0

In [14]:
table_inner.tail(3)

,label,layer_name,area_filled,perimeter,axis_major_length,axis_minor_length,eccentricity,area,intensity_mean,intensity_max,intensity_min
108,109,A9 p5d_labels,296.0,64.041631,21.987787,17.280386,0.618343,296.0,72.601351,146.0,27.0
109,110,A9 p5d_labels,46.0,24.485281,10.281764,5.986901,0.812986,46.0,52.065217,61.0,40.0
110,111,A9 p5d_labels,87.0,39.520815,17.591475,6.785633,0.922610,87.0,68.678161,99.0,37.0